### ISSUE TITLE
Vaadin 23.0.7 not working in Karaf 4.4.0

### ISSUE THREAD

**Issue by jochenwalz** [vaadin/osgi#93] opened 2022-05-19 17:56 UTC
When installing the base-starter-flow-karaf example with Vaadin 23.0.7 in Karaf 4.3.6, it works fine. When installing it in Karaf 4.4.0, the flow-osgi bundle throws an error (see below).

Can it be expected that Vaadin 23 should work with Karaf 4.4.0 (OSGi 8)? If not yet, is there a plan when this will be supported?

Vaadin flow version: 23.0.7
Java version: 17.0.2
Karaf version: 4.4.0
OSGi version: 8
OS version: Windows 10

Exception on startup:

```
2022-05-19T19:42:57,195 | ERROR | paxweb-config-3-thread-1 (deploy /) | PaxWebServletContextHandler      | 319 - org.ops4j.pax.web.pax-web-jetty - 8.0.2 | java.lang.reflect.InvocationTargetException
javax.servlet.ServletException: java.lang.reflect.InvocationTargetException
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.lambda$onStartup$2(ClassLoaderAwareServletContainerInitializer.java:103) ~[!/:23.0.5]
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.onStartup(ClassLoaderAwareServletContainerInitializer.java:122) ~[!/:23.0.5]
	at org.ops4j.pax.web.service.spi.servlet.SCIWrapper.onStartup(SCIWrapper.java:43) ~[!/:?]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.lambda$startContext$1(PaxWebServletContextHandler.java:211) ~[!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.startContext(PaxWebServletContextHandler.java:205) ~[!/:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916) ~[!/:9.4.46.v20220331]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[!/:9.4.46.v20220331]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.doStart(PaxWebServletContextHandler.java:261) ~[!/:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.ensureServletContextStarted(JettyServerWrapper.java:2255) ~[!/:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.visitTransactionStateChange(JettyServerWrapper.java:725) ~[!/:?]
	at org.ops4j.pax.web.service.spi.task.TransactionStateChange.accept(TransactionStateChange.java:35) ~[!/:?]
	at org.ops4j.pax.web.service.spi.task.Batch.accept(Batch.java:430) ~[!/:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerController.sendBatch(JettyServerController.java:168) ~[!/:?]
	at org.ops4j.pax.web.service.internal.HttpServiceEnabled$WebAppWebContainer.lambda$sendBatch$0(HttpServiceEnabled.java:2472) ~[?:?]
	at org.ops4j.pax.web.service.spi.model.ServerModel.lambda$run$2(ServerModel.java:534) ~[!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.lambda$onStartup$2(ClassLoaderAwareServletContainerInitializer.java:98) ~[!/:23.0.5]
	... 23 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.osgi.framework.Bundle.getResources(String)" because "this.bundle" is null
	at com.vaadin.flow.osgi.support.OSGiResourceProvider.getApplicationResources(OSGiResourceProvider.java:53) ~[!/:8.0.1]
	at com.vaadin.flow.server.startup.DefaultApplicationConfigurationFactory.getTokenFileFromClassloader(DefaultApplicationConfigurationFactory.java:178) ~[!/:23.0.5]
	at com.vaadin.flow.server.startup.DefaultApplicationConfigurationFactory.create(DefaultApplicationConfigurationFactory.java:117) ~[!/:23.0.5]
	at com.vaadin.flow.server.startup.ApplicationConfiguration.lambda$get$0(ApplicationConfiguration.java:67) ~[!/:23.0.5]
	at com.vaadin.flow.server.VaadinServletContext.getAttribute(VaadinServletContext.java:73) ~[!/:23.0.5]
	at com.vaadin.flow.server.startup.ApplicationConfiguration.get(ApplicationConfiguration.java:50) ~[!/:23.0.5]
	at com.vaadin.flow.server.startup.VaadinAppShellInitializer.init(VaadinAppShellInitializer.java:110) ~[!/:23.0.5]
	at com.vaadin.flow.server.startup.VaadinAppShellInitializer.initialize(VaadinAppShellInitializer.java:79) ~[!/:23.0.5]
	at com.vaadin.flow.server.startup.VaadinServletContextStartupInitializer.process(VaadinServletContextStartupInitializer.java:42) ~[!/:23.0.5]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.lambda$onStartup$2(ClassLoaderAwareServletContainerInitializer.java:98) ~[!/:23.0.5]
	... 23 more
```

**Comment by mcollovati** [comment] 2022-07-14 08:33
Seems to work correctly with Vaadin 23.1 , Karaf 4.4 and both Java 11 and 1.
The application starts and I cannot see errors on logs.

Only change was replacing `felix-http` feature with `http` and adding `http-whiteboard`
Perhaps this configuration may be better for the starter

**Comment by MarcinVaadin** [comment] 2022-08-08 12:31
According to https://github.com/vaadin/vaadin-flow-karaf-example/issues/100#issuecomment-1147385860 could you try checking it on latest 23.0?

**Comment by mcollovati** [comment] 2022-08-12 07:38
Can't reproduce the issue with latest flow-osgi on Vaadin 23.0 and 23.1.
However, karaf features in main-ui pom can be cleaned up.
Closing in favor of vaadin/vaadin-flow-karaf-example#100

**Closed by mcollovati** 2022-08-12 07:38 UTC
