### ISSUE TITLE
OSGi helping hand needed?

### ISSUE THREAD

**Issue by Sandared** [vaadin/osgi#11] opened 2021-01-06 13:43 UTC
Hi Vaadin Gurus :) 

I came across this repository through your recent [blogpost](https://vaadin.com/blog/re-introducing-osgi-support-for-npm-based-flow-projects) and am psyched to see this first verison of OSGi support 👍 

While digging through the code in this repository I saw several hard wires, e.g., 
```java
for (Bundle bundle : bundles) {
    if ("com.vaadin.flow.client".equals(bundle.getSymbolicName())) {
        return bundle.getResource(path);
    }
}
```
which IMHO are rather rare in a modern OSGi environment or maybe could be solved easier by leveraging SCR in other places of Vaadin too.

I would love to learn the requirements from Vaadin side for this OSGi integration and would like to offer my help in my free time if a helping hand is wanted/needed from your side.

Kind regards,
Thomas

**Comment by denis-anisimov** [comment] 2021-01-06 14:19
Thank you very much for your suggestion.
We will be very glad to get any help.
But this ticket doesn't look like an issue.
Do you see any exact issue which exists in the code or you may provide the steps to reproduce ?

The title of the ticket is rather a question.
If you see an issue please just make a ticket per issue.
Also you may create a PR to fix the issue but it's better to create a ticket for issue first to understand what PR fixes before the PR.

It's quite possible that some things may be solved in a better way.
So I will be happy to get any suggestion for improvement.
Please just note one quite important thing: OSGi is not the only container which we support. Flow code should work without any OSGi.
So any solution should not be OSGi centric only.
(the code which you referred in the main comment can be solved easily via OSGI service but that will require introducing OSGi related code into the pure `flow-client` resource bundle which doesn't know anything about OSGi, so I'm not convinced that this approach will be easier: but if you see really better approach please just feel free to make a PR).

**Comment by Sandared** [comment] 2021-01-06 15:23
Hi Denis,

yes sorry for misusing the ticketing system for that, but I didn't know where to put it else to get in contact the best way :/

The thing with OSGi is that it can be very unintrusive if used right, e.g., the OSGiResourceProvider for client resources could be rewritten to use a component that only exists if deployed into an OSGi container that also has SCR installed. 

If you don't want any OSGi dependencies in you flow-client bundle then you could achieve this by using a fragment bundle that comes from the OSGi integration project and attaches itself to the flow-client bundle if deployed in an OSGi runtime.
Within this fragment bundle you could create a special OSGIClientResourceProvider like this:

```java
@Component(service = OSGiClientResourceProvider)
public class OSGiClientResourceProvider {

   private Bundle bundle;

   @Activate
    void activate(BundleContext ctx) {
        bundle = ctx.getBundle();
    }

    public URL getClientResource(String path) {
        return bundle.getResource(path);
    }  
}
```
As the fragment bundle is attached to the flow-client bundle, it will be treated by the OSGi runtime as if it were part of the flow-client bundle and will therefore receive flow-client bundle's context and also gain access to its resources.
Then other Components in the OSGi integration could use this via `@Reference` which delegates reference injection to the SCR. This way you don't have to write code that handles the case that this component didn't start yet AND you don't have to pollute existing code.

If I had better insight into what your requirements are exactly for the OSGi integration I maybe could help in other places too, but I don't have yet the insight into the inne workings of Vaadin Flow and therefore might miss some important points. I only had some little experience with the code of Vaadin 8 where I wrote a small integration for OSGi once.

So if you think my input might help you in any way I would be glad to get in contact with you :) 

Kind regards,
Thomas

**Comment by denis-anisimov** [comment] 2021-01-07 05:47
Unfortunately I didn't get your suggestion.

I would like to avoid OSGi dependencies in the `flow-client` module just because this module has no Java code at all currently. This is pure resources module and there is no reason to introduce real Java code there just because of replacing 5 lines of code:
```
for (Bundle bundle : bundles) {
    if ("com.vaadin.flow.client".equals(bundle.getSymbolicName())) {
        return bundle.getResource(path);
    }
}
```

Could you please create a PR to demo and prove how it works. I'm still not sure that services approach will be easier even though I agree that using symbolic name to find the bundle is far away from the best approach.
Anyway, I don't even see how services can be used in your suggestion. I will be very glad to use the proper way if it really works.

I will close this ticket since it's not a real ticket. Let's proceed in the concrete issues/PRs.

**Closed by denis-anisimov** 2021-01-07 05:47 UTC
